### ISSUE TITLE
Future of legion_transform

### ISSUE THREAD

**Issue by CleanCut** [amethyst/legion_transform#4]
@AThilenius Are you on the Amethyst discord server?  I've been trying to reach you there, but no one knows you there.  I want to follow up on your comment in https://github.com/AThilenius/legion_transform/pull/3#issuecomment-656243172 about being so busy.

What are your long-term thoughts about maintainership of `legion_transform`?  Amethyst has decided to depend on it, and there are active, ongoing changes in two different soft forks.  There are likely to be a long tail of tweaks driven by Amethyst over the next weeks, months, and years.

Is this something you want to keep as an independent crate that you maintain personally? If so, would you consider granting write permissions to some key Amethyst developers so work can progress on this main repo even if you are busy?  If you _don't_ plan on maintaining this crate long term (as a maintainer myself, I wouldn't blame you), please let me know and we can discuss options.  Also, I'm happy to chat or voice-chat on the Amethyst Discord server if that's more convenient. My username is also @CleanCut there.

Update: There is also been a suggestion floating around to move this to `amethyst/legion_transform`.  We're waiting to hear your thoughts.

/cc @jojolepro @chemicstry

**Comment by AThilenius** [comment]
I'm `Xercsess (Alec)` on Discord. Posted this in the `ecs` channel as well:

Sorry I've been way out of the loop on Amethyst the last few months, life hit me up side the head plus a new job that takes most (all) my time :yum: I'm happy to have legion_transform moved under Amethyst. My time is indeed extremely limited, so passing off ownership of it would also be a good idea, and I'm happy to throw a bit of time in when I have it. The final impl of legion_transform is pretty straight forward, it's based very heavily on the Unity DOTs transform system.

**Comment by CleanCut** [comment]
Thanks, @AThilenius! I don't have any context on which to judge the suitability of `legion_transform` or not.  I'll poke around on discord later and see if I can find anyone with enough context to have a good discussion with.

Though I haven't yet caught up with all the news in the last few days, it appears this repository has already been migrated to `amethyst/legion_transform`, so I'll assume the future of this repo has been decided and acted upon.
